In [ ]:
# Question 1

In [1]:
import numpy as np
A = np.array([[3,4,2],
              [8,3,5],
              [6,6,7]])
B = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
C = np.dot(A,B)
print("Matrix Multiplication:\n",C)

Matrix Multiplication:
 [[ 33  42  51]
 [ 55  71  87]
 [ 79  98 117]]


In [3]:
A_T = A.transpose()
print("\nMatrix transpose:\n", A_T)


Matrix transpose:
 [[3 8 6]
 [4 3 6]
 [2 5 7]]


In [4]:
det = np.linalg.det(A)
print("\nMatrix determinant:\n", det)


Matrix determinant:
 -70.99999999999994


In [7]:
eigenvectors = np.linalg.eig(A)
print("\nEigenvectors:\n" , eigenvectors)


Eigenvectors:
 EigResult(eigenvalues=array([14.26352157,  1.68704377, -2.95056534]), eigenvectors=array([[-0.33580603, -0.48048145,  0.49624273],
       [-0.57104108, -0.26093155, -0.84267816],
       [-0.74909706,  0.83728866,  0.20889392]]))


In [ ]:
# Question 2

In [8]:
total_individuals = 300

female_baseball = 34
male_baseball = 34
total_baseball = 68

female_basketball = 52
total_female = 150

prob_male_given_baseball = male_baseball/total_baseball
prob_basketball_given_female = female_basketball/total_female

print(f"Probability that an individual is male,given that they prefer baseball: {prob_male_given_baseball:.4f}")

Probability that an individual is male,given that they prefer baseball: 0.5000


In [ ]:
print(f"Probability that an individual prefers basketball,given that they're female:{prob_male_given_baseball:.4f}")