In [1]:
# NumPy program that generates 4x4 array of random values and calculates the sum of each row

import numpy as np
random_array = np.random.rand(4, 4)
row_sums = np.sum(random_array, axis=1)

print("Random 4x4 Array:")
print(random_array)
print("\nSum of each row:")
print(row_sums)


Random 4x4 Array:
[[0.80871618 0.28857766 0.33831893 0.3485078 ]
 [0.01160112 0.30486072 0.9180283  0.85156119]
 [0.16589544 0.85033909 0.49398487 0.70868035]
 [0.80372324 0.64672112 0.25933524 0.09555107]]

Sum of each row:
[1.78412058 2.08605132 2.21889975 1.80533067]


In [2]:
# NumPy program that generates 5x5 array with randomly assigned values and then replace the minimum value in the array with 0

import numpy as np
random_array = np.random.rand(5, 5)
min_value = np.min(random_array)
random_array[random_array == min_value] = 0

print("Array with random values:\n", random_array)
print("Minimum value replaced with 0:\n", random_array)


Array with random values:
 [[0.84385175 0.71764721 0.45953041 0.61938132 0.83115601]
 [0.32039405 0.05473663 0.50022332 0.63143768 0.25532334]
 [0.21603946 0.37116809 0.         0.10618031 0.47078053]
 [0.05048407 0.98240199 0.94475615 0.41149524 0.75406526]
 [0.98900878 0.84491277 0.70500294 0.21468231 0.67478225]]
Minimum value replaced with 0:
 [[0.84385175 0.71764721 0.45953041 0.61938132 0.83115601]
 [0.32039405 0.05473663 0.50022332 0.63143768 0.25532334]
 [0.21603946 0.37116809 0.         0.10618031 0.47078053]
 [0.05048407 0.98240199 0.94475615 0.41149524 0.75406526]
 [0.98900878 0.84491277 0.70500294 0.21468231 0.67478225]]


In [3]:
# Pandas program to check whether alphabetic values present 

import pandas as pd
data = {
    'column1': ['abc', '123', 'a1b2', 'def', '456', 'ghi123', 'jkl']
}
df = pd.DataFrame(data)
df['is_alpha'] = df['column1'].str.isalpha()
print(df)

  column1  is_alpha
0     abc      True
1     123     False
2    a1b2     False
3     def      True
4     456     False
5  ghi123     False
6     jkl      True


In [4]:
# Pandas program to check whether only numeric values present 

import pandas as pd
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [1, 2, 'three', 4, 5],
    'C': [1.1, 2.2, 3.3, 4.4, 5.5]
}
df = pd.DataFrame(data)

def is_column_numeric(df, column_name):
    numeric_column = pd.to_numeric(df[column_name], errors='coerce')
    is_numeric = not numeric_column.isnull().any()
    return is_numeric
    
print("Column A is numeric:", is_column_numeric(df, 'A'))
print("Column B is numeric:", is_column_numeric(df, 'B'))
print("Column C is numeric:", is_column_numeric(df, 'C'))

Column A is numeric: True
Column B is numeric: False
Column C is numeric: True


In [5]:
# Pandas program to check whether only space is present 

import pandas as pd
data = {'column1': ['    ', '  ', 'abc', '  def', '', 'ghi  ']}
df = pd.DataFrame(data)

def is_only_spaces(s):
    return isinstance(s, str) and s.isspace()
df['only_spaces'] = df['column1'].apply(is_only_spaces)
print(df)

  column1  only_spaces
0                 True
1                 True
2     abc        False
3     def        False
4                False
5   ghi          False


In [6]:
# Pandas program to extract only non alphanumeric characters 

import pandas as pd
import re
data = {
    'text_column': ['Hello, World!', 'Pandas is #1', 'Python@3.8', 'Data:123!']
}
df = pd.DataFrame(data)

def extract_non_alphanumeric(s):
    return ''.join(re.findall(r'[^a-zA-Z0-9\s]', s))
df['non_alphanumeric'] = df['text_column'].apply(extract_non_alphanumeric)
print(df)

     text_column non_alphanumeric
0  Hello, World!               ,!
1   Pandas is #1                #
2     Python@3.8               @.
3      Data:123!               :!
